spring.application.name=spring-api
spring.datasource.url=jdbc:postgresql://localhost:5433/spring_coches
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# para arrancar la BDD con ciertos datos de partida (fichero data.sql), configuramos 2
propiedades:
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true