spring.application.name=spring_mongo_quispe

spring.data.mongodb.uri=mongodb+srv://root:rJBrULeFhvtdk3YQ@cluster0.xnoydpt.mongodb.net/filmoteca_quispe?retryWrites=true&w=majority

spring.data.mongodb.database=filmoteca_quispe

server.port=8081
logging.level.org.mongodb.driver=DEBUG